AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*