require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe LeaveRequestsController, type: :controller do

  let(:user) { User.new(Faker::Internet.email) }
  let(:token) { Token.new.encode(user) }

  # This should return the minimal set of attributes required to create a valid
  # LeaveRequest. As you add validations to LeaveRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      start_date: Faker::Date.forward(10),
      end_date: Faker::Date.forward(10),
      return_date: Faker::Date.forward(10),
      employee_id: Faker::Number.between(1, 10)
    }
  }

  let(:invalid_attributes) {
    {
      start_date: nil,
      end_date: Faker::Date.forward(10),
      return_date: Faker::Date.forward(10),
      employee_id: Faker::Number.between(1, 10)
    }
  }

  before do
    request.headers[:Token] = token
  end

  describe "GET #index" do
    it "returns a success response" do
      leave_request = LeaveRequest.create! valid_attributes
      get :index, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      leave_request = LeaveRequest.create! valid_attributes
      get :show, params: {id: leave_request.to_param}
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LeaveRequest" do
        expect {
        post :create, params: {leave_request: valid_attributes}
        }.to change(LeaveRequest, :count).by(1)
      end

      it "renders a JSON response with the new leave_request" do
        post :create, params: {leave_request: valid_attributes}
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(leave_request_url(LeaveRequest.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new leave_request" do
        post :create, params: {leave_request: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:start_date){Faker::Date.forward(10)}
      let(:end_date){Faker::Date.forward(10)}
      let(:return_date){Faker::Date.forward(10)}
      let(:employee_id){Faker::Number.between(1, 10)}
      let(:new_attributes) {
        {
          start_date: start_date,
          end_date: end_date,
          return_date: return_date,
          employee_id: employee_id
        }
      }

      it "updates the requested leave_request" do
        leave_request = LeaveRequest.create! valid_attributes
        put :update, params: {id: leave_request.to_param, leave_request: new_attributes}
        leave_request.reload
        expect(leave_request["start_date"]).to eq(start_date)
        expect(leave_request["end_date"]).to eq(end_date)
        expect(leave_request["return_date"]).to eq(return_date)
        expect(leave_request["employee_id"]).to eq(employee_id.to_s)
      end

      it "renders a JSON response with the leave_request" do
        leave_request = LeaveRequest.create! valid_attributes
        put :update, params: {id: leave_request.to_param, leave_request: valid_attributes}
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the leave_request" do
        leave_request = LeaveRequest.create! valid_attributes

        put :update, params: {id: leave_request.to_param, leave_request: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested leave_request" do
      leave_request = LeaveRequest.create! valid_attributes
      expect {
        delete :destroy, params: {id: leave_request.to_param}
      }.to change(LeaveRequest, :count).by(-1)
    end
  end

end
